server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://santino-mysql.cp2644kcsqkx.ap-northeast-2.rds.amazonaws.com:3306/board"
    username: "admin"
    password: "ichbinsantino0381"

#    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    url: "jdbc:mysql://127.0.0.1:3308/warehouseLocation"
#    username: "root"
#    password: "tkdals2"

#  jwt:
#    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbala"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true